"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'assets/black-bishop.png',
    'assets/black-king.png',
    'assets/black-knight.png',
    'assets/black-pawn.png',
    'assets/black-queen.png',
    'assets/black-rook.png',
    'assets/white-bishop.png',
    'assets/white-king.png',
    'assets/white-knight.png',
    'assets/white-pawn.png',
    'assets/white-queen.png',
    'assets/white-rook.png',
    'assets/bg.png',
    'assets/logo_big.png',
    'assets/logo_small.png',
    'assets/title.png',
]
OPTIONS = {
    'packages': ['pygame']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
